In [2]:
import torch

In [3]:
A = torch.arange(20*3).reshape(3, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]],
 
         [[40, 41, 42, 43],
          [44, 45, 46, 47],
          [48, 49, 50, 51],
          [52, 53, 54, 55],
          [56, 57, 58, 59]]]),
 torch.Size([3, 5, 4]),
 tensor(1770))

In [4]:
A_sum_axis = A.sum(axis=2)
A_sum_axis, A_sum_axis.shape

(tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150],
         [166, 182, 198, 214, 230]]),
 torch.Size([3, 5]))

In [6]:
A.cumsum(axis=0)

tensor([[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19]],

        [[ 20,  22,  24,  26],
         [ 28,  30,  32,  34],
         [ 36,  38,  40,  42],
         [ 44,  46,  48,  50],
         [ 52,  54,  56,  58]],

        [[ 60,  63,  66,  69],
         [ 72,  75,  78,  81],
         [ 84,  87,  90,  93],
         [ 96,  99, 102, 105],
         [108, 111, 114, 117]]])